language: r
cache: packages
os:
- linux
- osx
r_packages:
- jsonlite
- httr
- dplyr
- maps
- ISOcodes
warnings_are_errors: true
install:
- R -e 'devtools::install_deps(dep = T)'
script:
- R CMD build .
- R CMD check *tar.gz
